In [1]:
import pandas as pd

books = pd.read_csv("books_cleaned.csv")

In [2]:
books["categories"].value_counts().reset_index()

                    categories  count
0                      Fiction   2111
1             Juvenile Fiction    390
2    Biography & Autobiography    311
3                      History    207
4           Literary Criticism    124
..                         ...    ...
474               Conspiracies      1
475       Brothers and sisters      1
476             Rock musicians      1
477             Community life      1
478    Indic fiction (English)      1

[479 rows x 2 columns]

In [3]:
category_mapping = {'Fiction' : "Fiction",
 'Juvenile Fiction': "Children's Fiction",
 'Biography & Autobiography': "Nonfiction",
 'History': "Nonfiction",
 'Literary Criticism': "Nonfiction",
 'Philosophy': "Nonfiction",
 'Religion': "Nonfiction",
 'Comics & Graphic Novels': "Fiction",
 'Drama': "Fiction",
 'Juvenile Nonfiction': "Children's Nonfiction",
 'Science': "Nonfiction",
 'Poetry': "Fiction"}

books["simple_categories"] = books["categories"].map(category_mapping)

In [4]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,missing_desc,age_book,title_and_subtitle,tagged_description,simple_categories
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,1,22.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...,Fiction
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,1,26.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...,NaN
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,1,33.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine...",Fiction
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,1,24.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...,NaN
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,1,24.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,1,23.0,Mistaken Identity,9788172235222 On A Train Journey Home To North...,NaN
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,1,24.0,Journey to the East,9788173031014 This book tells the tale of a ma...,NaN
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,1,23.0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...,NaN
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,1,27.0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...,Nonfiction
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,1,45.0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...,Nonfiction

In [4]:
books[~(books["simple_categories"].isna())]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,missing_desc,age_book,title_and_subtitle,tagged_description,simple_categories
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,1,22.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...,Fiction
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,1,33.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine...",Fiction
8,9780006482079,0006482074,Warhost of Vastmark,Janny Wurts,Fiction,http://books.google.com/books/content?id=uOL0f...,"Tricked once more by his wily half-brother, Ly...",1995.0,4.03,522.0,2966.0,1,31.0,Warhost of Vastmark,9780006482079 Tricked once more by his wily ha...,Fiction
30,9780006646006,000664600X,Ocean Star Express,Mark Haddon;Peter Sutton,Juvenile Fiction,http://books.google.com/books/content?id=I2QZA...,Joe and his parents are enjoying a summer holi...,2002.0,3.50,32.0,1.0,1,24.0,Ocean Star Express,9780006646006 Joe and his parents are enjoying...,Children's Fiction
46,9780007121014,0007121016,Taken at the Flood,Agatha Christie,Fiction,http://books.google.com/books/content?id=3gWlx...,A Few Weeks After Marrying An Attractive Young...,2002.0,3.71,352.0,8852.0,1,24.0,Taken at the Flood,9780007121014 A Few Weeks After Marrying An At...,Fiction
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5178,9781933648279,1933648279,Night Has a Thousand Eyes,Cornell Woolrich,Fiction,http://books.google.com/books/content?id=3Gk6s...,"""Cornell Woolrich's novels define the essence ...",2007.0,3.77,344.0,680.0,1,19.0,Night Has a Thousand Eyes,"9781933648279 ""Cornell Woolrich's novels defin...",Fiction
5188,9784770028969,4770028962,Coin Locker Babies,村上龍,Fiction,http://books.google.com/books/content?id=87DJw...,Rescued from the lockers in which they were le...,2002.0,3.75,393.0,5560.0,1,24.0,Coin Locker Babies,9784770028969 Rescued from the lockers in whic...,Fiction
5189,9788122200850,8122200850,"Cry, the Peacock",Anita Desai,Fiction,http://books.google.com/books/content?id=_QKwV...,This book is the story of a young girl obsesse...,1980.0,3.22,218.0,134.0,1,46.0,"Cry, the Peacock",9788122200850 This book is the story of a youn...,Fiction
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,1,27.0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...,Nonfiction
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,1,45.0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...,Nonfiction

In [7]:
!pip install torch-directml ipykernel

Defaulting to user installation because normal site-packages is not writeable
Collecting torch-directml
  Using cached torch_directml-0.2.5.dev240914-cp312-cp312-win_amd64.whl.metadata (6.3 kB)
Requirement already satisfied: ipykernel in c:\programdata\anaconda3\lib\site-packages (6.28.0)
Requirement already satisfied: torch==2.4.1 in c:\users\user\appdata\roaming\python\python312\site-packages (from torch-directml) (2.4.1)
Collecting torchvision==0.19.1 (from torch-directml)
  Using cached torchvision-0.19.1-cp312-cp312-win_amd64.whl.metadata (6.1 kB)
Requirement already satisfied: filelock in c:\programdata\anaconda3\lib\site-packages (from torch==2.4.1->torch-directml) (3.13.1)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\users\user\appdata\roaming\python\python312\site-packages (from torch==2.4.1->torch-directml) (4.15.0)
Requirement already satisfied: sympy in c:\users\user\appdata\roaming\python\python312\site-packages (from torch==2.4.1->torch-directml) (1.14.0)
Requirement already satisfied: networkx in c:\programdata\anaconda3\lib\site-packages (from torch==2.4.1->torch-directml) (3.3)
Requirement already satisfied: jinja2 in c:\programdata\anaconda3\lib\site-packages (from torch==2.4.1->torch-directml) (3.1.4)
Requirement already satisfied: fsspec in c:\programdata\anaconda3\lib\site-packages (from torch==2.4.1->torch-directml) (2024.6.1)
Requirement already satisfied: setuptools in c:\programdata\anaconda3\lib\site-packages (from torch==2.4.1->torch-directml) (75.1.0)
Requirement already satisfied: numpy in c:\users\user\appdata\roaming\python\python312\site-packages (from torchvision==0.19.1->torch-directml) (1.26.4)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\users\user\appdata\roaming\python\python312\site-packages (from torchvision==0.19.1->torch-directml) (12.0.0)
Requirement already satisfied: comm>=0.1.1 in c:\programdata\anaconda3\lib\site-packages (from ipykernel) (0.2.1)
Requirement already satisfied: debugpy>=1.6.5 in c:\programdata\anaconda3\lib\site-packages (from ipykernel) (1.6.7)
Requirement already satisfied: ipython>=7.23.1 in c:\programdata\anaconda3\lib\site-packages (from ipykernel) (8.27.0)
Requirement already satisfied: jupyter-client>=6.1.12 in c:\programdata\anaconda3\lib\site-packages (from ipykernel) (8.6.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\programdata\anaconda3\lib\site-packages (from ipykernel) (5.7.2)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\programdata\anaconda3\lib\site-packages (from ipykernel) (0.1.6)
Requirement already satisfied: nest-asyncio in c:\programdata\anaconda3\lib\site-packages (from ipykernel) (1.6.0)
Requirement already satisfied: packaging in c:\programdata\anaconda3\lib\site-packages (from ipykernel) (24.1)
Requirement already satisfied: psutil in c:\programdata\anaconda3\lib\site-packages (from ipykernel) (5.9.0)
Requirement already satisfied: pyzmq>=24 in c:\programdata\anaconda3\lib\site-packages (from ipykernel) (25.1.2)
Requirement already satisfied: tornado>=6.1 in c:\programdata\anaconda3\lib\site-packages (from ipykernel) (6.4.1)
Requirement already satisfied: traitlets>=5.4.0 in c:\programdata\anaconda3\lib\site-packages (from ipykernel) (5.14.3)
Requirement already satisfied: decorator in c:\programdata\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\programdata\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel) (0.19.1)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\programdata\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in c:\programdata\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel) (2.15.1)
Requirement already satisfied: stack-data in c:\programdata\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel) (0.2.0)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from jupyter-client>=6.1.12->ipykernel) (2.9.0.post0)
Requirement already satisfied: platformdirs>=2.5 in c:\programdata\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel) (3.10.0)
Requirement already satisfied: pywin32>=300 in c:\programdata\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel) (305.1)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in c:\programdata\anaconda3\lib\site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel) (0.8.3)
Requirement already satisfied: wcwidth in c:\programdata\anaconda3\lib\site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel) (0.2.5)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->jupyter-client>=6.1.12->ipykernel) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\programdata\anaconda3\lib\site-packages (from jinja2->torch==2.4.1->torch-directml) (2.1.3)
Requirement already satisfied: executing in c:\programdata\anaconda3\lib\site-packages (from stack-data->ipython>=7.23.1->ipykernel) (0.8.3)
Requirement already satisfied: asttokens in c:\programdata\anaconda3\lib\site-packages (from stack-data->ipython>=7.23.1->ipykernel) (2.0.5)
Requirement already satisfied: pure-eval in c:\programdata\anaconda3\lib\site-packages (from stack-data->ipython>=7.23.1->ipykernel) (0.2.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\programdata\anaconda3\lib\site-packages (from sympy->torch==2.4.1->torch-directml) (1.3.0)
Using cached torch_directml-0.2.5.dev240914-cp312-cp312-win_amd64.whl (9.0 MB)
Using cached torchvision-0.19.1-cp312-cp312-win_amd64.whl (1.3 MB)
Installing collected packages: torchvision, torch-directml
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.24.0
    Uninstalling torchvision-0.24.0:
      Successfully uninstalled torchvision-0.24.0
Successfully installed torch-directml-0.2.5.dev240914 torchvision-0.19.1

WARNING: Ignoring invalid distribution ~orch (C:\Users\user\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~orch (C:\Users\user\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~orch (C:\Users\user\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~orch (C:\Users\user\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~orch (C:\Users\user\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~orch (C:\Users\user\AppData\Roaming\Python\Python312\site-packages)

Defaulting to user installation because normal site-packages is not writeable
Collecting torch-directml
  Using cached torch_directml-0.2.5.dev240914-cp312-cp312-win_amd64.whl.metadata (6.3 kB)
Requirement already satisfied: ipykernel in c:\programdata\anaconda3\lib\site-packages (6.28.0)
Collecting torch==2.4.1 (from torch-directml)
  Using cached torch-2.4.1-cp312-cp312-win_amd64.whl.metadata (27 kB)
Collecting torchvision==0.19.1 (from torch-directml)
  Using cached torchvision-0.19.1-cp312-cp312-win_amd64.whl.metadata (6.1 kB)
Requirement already satisfied: filelock in c:\programdata\anaconda3\lib\site-packages (from torch==2.4.1->torch-directml) (3.13.1)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\users\user\appdata\roaming\python\python312\site-packages (from torch==2.4.1->torch-directml) (4.15.0)
Requirement already satisfied: sympy in c:\users\user\appdata\roaming\python\python312\site-packages (from torch==2.4.1->torch-directml) (1.14.0)
Requirement already satisfied: networkx in c:\programdata\anaconda3\lib\site-packages (from torch==2.4.1->torch-directml) (3.3)
Requirement already satisfied: jinja2 in c:\programdata\anaconda3\lib\site-packages (from torch==2.4.1->torch-directml) (3.1.4)
Requirement already satisfied: fsspec in c:\programdata\anaconda3\lib\site-packages (from torch==2.4.1->torch-directml) (2024.6.1)
Requirement already satisfied: setuptools in c:\programdata\anaconda3\lib\site-packages (from torch==2.4.1->torch-directml) (75.1.0)
Requirement already satisfied: numpy in c:\users\user\appdata\roaming\python\python312\site-packages (from torchvision==0.19.1->torch-directml) (1.26.4)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\users\user\appdata\roaming\python\python312\site-packages (from torchvision==0.19.1->torch-directml) (12.0.0)
Requirement already satisfied: comm>=0.1.1 in c:\programdata\anaconda3\lib\site-packages (from ipykernel) (0.2.1)
Requirement already satisfied: debugpy>=1.6.5 in c:\programdata\anaconda3\lib\site-packages (from ipykernel) (1.6.7)
Requirement already satisfied: ipython>=7.23.1 in c:\programdata\anaconda3\lib\site-packages (from ipykernel) (8.27.0)
Requirement already satisfied: jupyter-client>=6.1.12 in c:\programdata\anaconda3\lib\site-packages (from ipykernel) (8.6.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\programdata\anaconda3\lib\site-packages (from ipykernel) (5.7.2)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\programdata\anaconda3\lib\site-packages (from ipykernel) (0.1.6)
Requirement already satisfied: nest-asyncio in c:\programdata\anaconda3\lib\site-packages (from ipykernel) (1.6.0)
Requirement already satisfied: packaging in c:\programdata\anaconda3\lib\site-packages (from ipykernel) (24.1)
Requirement already satisfied: psutil in c:\programdata\anaconda3\lib\site-packages (from ipykernel) (5.9.0)
Requirement already satisfied: pyzmq>=24 in c:\programdata\anaconda3\lib\site-packages (from ipykernel) (25.1.2)
Requirement already satisfied: tornado>=6.1 in c:\programdata\anaconda3\lib\site-packages (from ipykernel) (6.4.1)
Requirement already satisfied: traitlets>=5.4.0 in c:\programdata\anaconda3\lib\site-packages (from ipykernel) (5.14.3)
Requirement already satisfied: decorator in c:\programdata\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\programdata\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel) (0.19.1)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\programdata\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in c:\programdata\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel) (2.15.1)
Requirement already satisfied: stack-data in c:\programdata\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel) (0.2.0)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from jupyter-client>=6.1.12->ipykernel) (2.9.0.post0)
Requirement already satisfied: platformdirs>=2.5 in c:\programdata\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel) (3.10.0)
Requirement already satisfied: pywin32>=300 in c:\programdata\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel) (305.1)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in c:\programdata\anaconda3\lib\site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel) (0.8.3)
Requirement already satisfied: wcwidth in c:\programdata\anaconda3\lib\site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel) (0.2.5)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->jupyter-client>=6.1.12->ipykernel) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\programdata\anaconda3\lib\site-packages (from jinja2->torch==2.4.1->torch-directml) (2.1.3)
Requirement already satisfied: executing in c:\programdata\anaconda3\lib\site-packages (from stack-data->ipython>=7.23.1->ipykernel) (0.8.3)
Requirement already satisfied: asttokens in c:\programdata\anaconda3\lib\site-packages (from stack-data->ipython>=7.23.1->ipykernel) (2.0.5)
Requirement already satisfied: pure-eval in c:\programdata\anaconda3\lib\site-packages (from stack-data->ipython>=7.23.1->ipykernel) (0.2.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\programdata\anaconda3\lib\site-packages (from sympy->torch==2.4.1->torch-directml) (1.3.0)
Downloading torch_directml-0.2.5.dev240914-cp312-cp312-win_amd64.whl (9.0 MB)
   ---------------------------------------- 0.0/9.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.0 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.0 MB 2.2 MB/s eta 0:00:04
   ----- ---------------------------------- 1.3/9.0 MB 2.3 MB/s eta 0:00:04
   ------- -------------------------------- 1.6/9.0 MB 2.3 MB/s eta 0:00:04
   --------- ------------------------------ 2.1/9.0 MB 2.2 MB/s eta 0:00:04
   ---------- ----------------------------- 2.4/9.0 MB 2.1 MB/s eta 0:00:04
   ------------ --------------------------- 2.9/9.0 MB 2.2 MB/s eta 0:00:03
   -------------- ------------------------- 3.1/9.0 MB 2.2 MB/s eta 0:00:03
   ---------------- ----------------------- 3.7/9.0 MB 2.1 MB/s eta 0:00:03
   ----------------- ---------------------- 3.9/9.0 MB 2.0 MB/s eta 0:00:03
   ----------------- ---------------------- 3.9/9.0 MB 2.0 MB/s eta 0:00:03
   ------------------ --------------------- 4.2/9.0 MB 1.8 MB/s eta 0:00:03
   --------------------- ------------------ 4.7/9.0 MB 1.8 MB/s eta 0:00:03
   ----------------------- ---------------- 5.2/9.0 MB 1.9 MB/s eta 0:00:02
   ------------------------- -------------- 5.8/9.0 MB 1.9 MB/s eta 0:00:02
   ---------------------------- ----------- 6.3/9.0 MB 1.9 MB/s eta 0:00:02
   ----------------------------- ---------- 6.6/9.0 MB 1.9 MB/s eta 0:00:02
   ------------------------------- -------- 7.1/9.0 MB 2.0 MB/s eta 0:00:01
   --------------------------------- ------ 7.6/9.0 MB 2.0 MB/s eta 0:00:01
   ------------------------------------ --- 8.1/9.0 MB 2.0 MB/s eta 0:00:01
   -------------------------------------- - 8.7/9.0 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------- 9.0/9.0 MB 2.0 MB/s eta 0:00:00
Downloading torch-2.4.1-cp312-cp312-win_amd64.whl (199.4 MB)
   ---------------------------------------- 0.0/199.4 MB ? eta -:--:--
   ---------------------------------------- 0.3/199.4 MB ? eta -:--:--
   ---------------------------------------- 0.8/199.4 MB 2.2 MB/s eta 0:01:30
   ---------------------------------------- 1.3/199.4 MB 2.3 MB/s eta 0:01:26
   ---------------------------------------- 1.8/199.4 MB 2.3 MB/s eta 0:01:25
   ---------------------------------------- 2.1/199.4 MB 2.1 MB/s eta 0:01:35
   ---------------------------------------- 2.4/199.4 MB 2.1 MB/s eta 0:01:33
    --------------------------------------- 2.9/199.4 MB 2.1 MB/s eta 0:01:35
    --------------------------------------- 3.4/199.4 MB 2.1 MB/s eta 0:01:36
    --------------------------------------- 3.7/199.4 MB 2.1 MB/s eta 0:01:35
    --------------------------------------- 4.2/199.4 MB 2.1 MB/s eta 0:01:34
    --------------------------------------- 4.7/199.4 MB 2.1 MB/s eta 0:01:32
   - -------------------------------------- 5.2/199.4 MB 2.1 MB/s eta 0:01:31
   - -------------------------------------- 5.8/199.4 MB 2.1 MB/s eta 0:01:31
   - -------------------------------------- 6.0/199.4 MB 2.2 MB/s eta 0:01:30
   - -------------------------------------- 6.6/199.4 MB 2.2 MB/s eta 0:01:30
   - -------------------------------------- 7.1/199.4 MB 2.2 MB/s eta 0:01:29
   - -------------------------------------- 7.6/199.4 MB 2.2 MB/s eta 0:01:29
   - -------------------------------------- 7.9/199.4 MB 2.2 MB/s eta 0:01:28
   - -------------------------------------- 8.4/199.4 MB 2.1 MB/s eta 0:01:29
   - -------------------------------------- 8.7/199.4 MB 2.1 MB/s eta 0:01:29
   - -------------------------------------- 8.9/199.4 MB 2.1 MB/s eta 0:01:31
   - -------------------------------------- 9.4/199.4 MB 2.1 MB/s eta 0:01:31
   - -------------------------------------- 9.7/199.4 MB 2.1 MB/s eta 0:01:30
   -- ------------------------------------- 10.2/199.4 MB 2.1 MB/s eta 0:01:30
   -- ------------------------------------- 10.7/199.4 MB 2.1 MB/s eta 0:01:30
   -- ------------------------------------- 11.3/199.4 MB 2.1 MB/s eta 0:01:29
   -- ------------------------------------- 11.8/199.4 MB 2.1 MB/s eta 0:01:28
   -- ------------------------------------- 12.1/199.4 MB 2.1 MB/s eta 0:01:28
   -- ------------------------------------- 12.6/199.4 MB 2.1 MB/s eta 0:01:28
   -- ------------------------------------- 13.1/199.4 MB 2.2 MB/s eta 0:01:27
   -- ------------------------------------- 13.6/199.4 MB 2.2 MB/s eta 0:01:26
   -- ------------------------------------- 14.2/199.4 MB 2.2 MB/s eta 0:01:26
   -- ------------------------------------- 14.7/199.4 MB 2.2 MB/s eta 0:01:26
   -- ------------------------------------- 14.9/199.4 MB 2.2 MB/s eta 0:01:25
   --- ------------------------------------ 15.5/199.4 MB 2.2 MB/s eta 0:01:25
   --- ------------------------------------ 16.0/199.4 MB 2.2 MB/s eta 0:01:24
   --- ------------------------------------ 16.5/199.4 MB 2.2 MB/s eta 0:01:24
   --- ------------------------------------ 17.0/199.4 MB 2.2 MB/s eta 0:01:24
   --- ------------------------------------ 17.3/199.4 MB 2.2 MB/s eta 0:01:24
   --- ------------------------------------ 17.6/199.4 MB 2.2 MB/s eta 0:01:25
   --- ------------------------------------ 17.8/199.4 MB 2.2 MB/s eta 0:01:25
   --- ------------------------------------ 18.1/199.4 MB 2.1 MB/s eta 0:01:26
   --- ------------------------------------ 18.1/199.4 MB 2.1 MB/s eta 0:01:26
   --- ------------------------------------ 18.1/199.4 MB 2.1 MB/s eta 0:01:26
   --- ------------------------------------ 18.1/199.4 MB 2.1 MB/s eta 0:01:26
   --- ------------------------------------ 18.1/199.4 MB 2.1 MB/s eta 0:01:26
   --- ------------------------------------ 18.1/199.4 MB 2.1 MB/s eta 0:01:26
   --- ------------------------------------ 18.1/199.4 MB 2.1 MB/s eta 0:01:26
   --- ------------------------------------ 18.4/199.4 MB 1.8 MB/s eta 0:01:39
   --- ------------------------------------ 18.9/199.4 MB 1.8 MB/s eta 0:01:39
   --- ------------------------------------ 19.1/199.4 MB 1.8 MB/s eta 0:01:39
   --- ------------------------------------ 19.7/199.4 MB 1.8 MB/s eta 0:01:38
   ---- ----------------------------------- 20.2/199.4 MB 1.9 MB/s eta 0:01:37
   ---- ----------------------------------- 20.7/199.4 MB 1.9 MB/s eta 0:01:37
   ---- ----------------------------------- 21.0/199.4 MB 1.9 MB/s eta 0:01:36
   ---- ----------------------------------- 21.5/199.4 MB 1.9 MB/s eta 0:01:36
   ---- ----------------------------------- 22.0/199.4 MB 1.9 MB/s eta 0:01:35
   ---- ----------------------------------- 22.5/199.4 MB 1.9 MB/s eta 0:01:34
   ---- ----------------------------------- 23.1/199.4 MB 1.9 MB/s eta 0:01:34
   ---- ----------------------------------- 23.6/199.4 MB 1.9 MB/s eta 0:01:33
   ---- ----------------------------------- 23.9/199.4 MB 1.9 MB/s eta 0:01:33
   ---- ----------------------------------- 24.4/199.4 MB 1.9 MB/s eta 0:01:32
   ---- ----------------------------------- 24.9/199.4 MB 1.9 MB/s eta 0:01:32
   ----- ---------------------------------- 25.2/199.4 MB 1.9 MB/s eta 0:01:31
   ----- ---------------------------------- 25.7/199.4 MB 1.9 MB/s eta 0:01:31
   ----- ---------------------------------- 25.7/199.4 MB 1.9 MB/s eta 0:01:31
   ----- ---------------------------------- 26.5/199.4 MB 1.9 MB/s eta 0:01:31
   ----- ---------------------------------- 27.0/199.4 MB 1.9 MB/s eta 0:01:31
   ----- ---------------------------------- 27.3/199.4 MB 1.9 MB/s eta 0:01:30
   ----- ---------------------------------- 27.8/199.4 MB 1.9 MB/s eta 0:01:30
   ----- ---------------------------------- 28.3/199.4 MB 1.9 MB/s eta 0:01:29
   ----- ---------------------------------- 28.8/199.4 MB 1.9 MB/s eta 0:01:29
   ----- ---------------------------------- 29.4/199.4 MB 1.9 MB/s eta 0:01:28
   ----- ---------------------------------- 29.9/199.4 MB 1.9 MB/s eta 0:01:28
   ------ --------------------------------- 30.4/199.4 MB 2.0 MB/s eta 0:01:27
   ------ --------------------------------- 30.9/199.4 MB 2.0 MB/s eta 0:01:26
   ------ --------------------------------- 31.5/199.4 MB 2.0 MB/s eta 0:01:26
   ------ --------------------------------- 31.7/199.4 MB 2.0 MB/s eta 0:01:26
   ------ --------------------------------- 32.2/199.4 MB 2.0 MB/s eta 0:01:25
   ------ --------------------------------- 32.8/199.4 MB 2.0 MB/s eta 0:01:25
   ------ --------------------------------- 33.0/199.4 MB 2.0 MB/s eta 0:01:25
   ------ --------------------------------- 33.6/199.4 MB 2.0 MB/s eta 0:01:25
   ------ --------------------------------- 34.1/199.4 MB 2.0 MB/s eta 0:01:24
   ------ --------------------------------- 34.6/199.4 MB 2.0 MB/s eta 0:01:24
   ------ --------------------------------- 34.9/199.4 MB 2.0 MB/s eta 0:01:24
   ------- -------------------------------- 35.1/199.4 MB 2.0 MB/s eta 0:01:23
   ------- -------------------------------- 35.4/199.4 MB 2.0 MB/s eta 0:01:24
   ------- -------------------------------- 35.9/199.4 MB 2.0 MB/s eta 0:01:23
   ------- -------------------------------- 36.4/199.4 MB 2.0 MB/s eta 0:01:23
   ------- -------------------------------- 37.0/199.4 MB 2.0 MB/s eta 0:01:23
   ------- -------------------------------- 37.5/199.4 MB 2.0 MB/s eta 0:01:22
   ------- -------------------------------- 37.7/199.4 MB 2.0 MB/s eta 0:01:22
   ------- -------------------------------- 37.7/199.4 MB 2.0 MB/s eta 0:01:22
   ------- -------------------------------- 37.7/199.4 MB 2.0 MB/s eta 0:01:22
   ------- -------------------------------- 37.7/199.4 MB 2.0 MB/s eta 0:01:22
   ------- -------------------------------- 37.7/199.4 MB 2.0 MB/s eta 0:01:22
   ------- -------------------------------- 37.7/199.4 MB 2.0 MB/s eta 0:01:22
   ------- -------------------------------- 37.7/199.4 MB 2.0 MB/s eta 0:01:22
   ------- -------------------------------- 37.7/199.4 MB 2.0 MB/s eta 0:01:22
   ------- -------------------------------- 37.7/199.4 MB 2.0 MB/s eta 0:01:22
   ------- -------------------------------- 37.7/199.4 MB 2.0 MB/s eta 0:01:22
   ------- -------------------------------- 37.7/199.4 MB 2.0 MB/s eta 0:01:22
   ------- -------------------------------- 37.7/199.4 MB 2.0 MB/s eta 0:01:22
   ------- -------------------------------- 38.3/199.4 MB 1.8 MB/s eta 0:01:31
   ------- -------------------------------- 38.8/199.4 MB 1.8 MB/s eta 0:01:31
   ------- -------------------------------- 39.1/199.4 MB 1.8 MB/s eta 0:01:31
   ------- -------------------------------- 39.3/199.4 MB 1.8 MB/s eta 0:01:31
   ------- -------------------------------- 39.6/199.4 MB 1.8 MB/s eta 0:01:31
   -------- ------------------------------- 40.1/199.4 MB 1.8 MB/s eta 0:01:30
   -------- ------------------------------- 40.6/199.4 MB 1.8 MB/s eta 0:01:30
   -------- ------------------------------- 41.2/199.4 MB 1.8 MB/s eta 0:01:29
   -------- ------------------------------- 41.7/199.4 MB 1.8 MB/s eta 0:01:29
   -------- ------------------------------- 42.2/199.4 MB 1.8 MB/s eta 0:01:28
   -------- ------------------------------- 42.5/199.4 MB 1.8 MB/s eta 0:01:28
   -------- ------------------------------- 43.0/199.4 MB 1.8 MB/s eta 0:01:27
   -------- ------------------------------- 43.5/199.4 MB 1.8 MB/s eta 0:01:27
   -------- ------------------------------- 43.8/199.4 MB 1.8 MB/s eta 0:01:27
   -------- ------------------------------- 44.0/199.4 MB 1.8 MB/s eta 0:01:27
   -------- ------------------------------- 44.6/199.4 MB 1.8 MB/s eta 0:01:26
   --------- ------------------------------ 45.1/199.4 MB 1.8 MB/s eta 0:01:26
   --------- ------------------------------ 45.4/199.4 MB 1.8 MB/s eta 0:01:26
   --------- ------------------------------ 45.9/199.4 MB 1.8 MB/s eta 0:01:25
   --------- ------------------------------ 46.4/199.4 MB 1.8 MB/s eta 0:01:25
   --------- ------------------------------ 46.7/199.4 MB 1.8 MB/s eta 0:01:25
   --------- ------------------------------ 46.7/199.4 MB 1.8 MB/s eta 0:01:25
   --------- ------------------------------ 47.2/199.4 MB 1.8 MB/s eta 0:01:25
   --------- ------------------------------ 47.4/199.4 MB 1.8 MB/s eta 0:01:25
   --------- ------------------------------ 47.7/199.4 MB 1.8 MB/s eta 0:01:25
   --------- ------------------------------ 48.0/199.4 MB 1.8 MB/s eta 0:01:25
   --------- ------------------------------ 48.5/199.4 MB 1.8 MB/s eta 0:01:25
   --------- ------------------------------ 48.8/199.4 MB 1.8 MB/s eta 0:01:24
   --------- ------------------------------ 49.3/199.4 MB 1.8 MB/s eta 0:01:24
   --------- ------------------------------ 49.5/199.4 MB 1.8 MB/s eta 0:01:24
   ---------- ----------------------------- 50.1/199.4 MB 1.8 MB/s eta 0:01:24
   ---------- ----------------------------- 50.6/199.4 MB 1.8 MB/s eta 0:01:23
   ---------- ----------------------------- 50.9/199.4 MB 1.8 MB/s eta 0:01:23
   ---------- ----------------------------- 51.4/199.4 MB 1.8 MB/s eta 0:01:23
   ---------- ----------------------------- 51.9/199.4 MB 1.8 MB/s eta 0:01:22
   ---------- ----------------------------- 52.4/199.4 MB 1.8 MB/s eta 0:01:22
   ---------- ----------------------------- 53.0/199.4 MB 1.8 MB/s eta 0:01:21
   ---------- ----------------------------- 53.2/199.4 MB 1.8 MB/s eta 0:01:21
   ---------- ----------------------------- 53.7/199.4 MB 1.8 MB/s eta 0:01:21
   ---------- ----------------------------- 54.3/199.4 MB 1.8 MB/s eta 0:01:20
   ---------- ----------------------------- 54.5/199.4 MB 1.8 MB/s eta 0:01:20
   ----------- ---------------------------- 55.1/199.4 MB 1.8 MB/s eta 0:01:20
   ----------- ---------------------------- 55.6/199.4 MB 1.8 MB/s eta 0:01:19
   ----------- ---------------------------- 56.1/199.4 MB 1.8 MB/s eta 0:01:19
   ----------- ---------------------------- 56.4/199.4 MB 1.8 MB/s eta 0:01:19
   ----------- ---------------------------- 56.9/199.4 MB 1.8 MB/s eta 0:01:18
   ----------- ---------------------------- 57.4/199.4 MB 1.8 MB/s eta 0:01:18
   ----------- ---------------------------- 57.9/199.4 MB 1.8 MB/s eta 0:01:18
   ----------- ---------------------------- 58.5/199.4 MB 1.8 MB/s eta 0:01:18
   ----------- ---------------------------- 58.7/199.4 MB 1.8 MB/s eta 0:01:17
   ----------- ---------------------------- 59.2/199.4 MB 1.8 MB/s eta 0:01:17
   ----------- ---------------------------- 59.8/199.4 MB 1.8 MB/s eta 0:01:17
   ------------ --------------------------- 60.3/199.4 MB 1.8 MB/s eta 0:01:17
   ------------ --------------------------- 60.6/199.4 MB 1.8 MB/s eta 0:01:16

  WARNING: The scripts convert-caffe2-to-onnx.exe, convert-onnx-to-caffe2.exe and torchrun.exe are installed in 'C:\Users\user\AppData\Roaming\Python\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

In [8]:
import os
# Set the cache directory to A: before importing Hugging Face libraries
os.environ["HF_HOME"] = "A:/huggingface_cache"
import torch_directml
from transformers import pipeline

# Create the DirectML device
dml_device = torch_directml.device()

fiction_categories = ["Fiction", "Nonfiction"]

pipe = pipeline("zero-shot-classification",
                model="facebook/bart-large-mnli",
                device=dml_device)

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Device set to use privateuseone:0

In [9]:
sequence = books.loc[books["simple_categories"] == "Fiction", "description"].reset_index(drop=True)[0]

In [10]:
pipe(sequence, fiction_categories)

C:\Users\user\AppData\Roaming\Python\Python312\site-packages\torch\functional.py:976: UserWarning: The operator 'aten::unique_consecutive' is not currently supported on the DML backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at C:\__w\1\s\pytorch-directml-plugin\torch_directml\csrc\dml\dml_cpu_fallback.cpp:17.)
  output, inverse_indices, counts = _VF.unique_consecutive(  # type: ignore[attr-defined]

{'sequence': 'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.',
 'labels': ['Fiction', 'Nonfiction'],
 'scores': [0.8438271880149841, 0.15617287158966064]}

In [11]:
import numpy as np

max_index = np.argmax(pipe(sequence, fiction_categories)["scores"])
max_label = pipe(sequence, fiction_categories)["labels"][max_index]
max_label

'Fiction'

In [12]:
def generate_predictions(sequence, categories):
    predictions = pipe(sequence, categories)
    max_index = np.argmax(predictions["scores"])
    max_label = predictions["labels"][max_index]
    return max_label

In [13]:
from tqdm import tqdm

actual_cats = []
predicted_cats = []

for i in tqdm(range(0, 300)):
    sequence = books.loc[books["simple_categories"] == "Fiction", "description"].reset_index(drop=True)[i]
    predicted_cats += [generate_predictions(sequence, fiction_categories)]
    actual_cats += ["Fiction"]

100%|████████████████████████████████████████████████████████████████████████████████| 300/300 [03:18<00:00,  1.51it/s]

In [14]:
for i in tqdm(range(0, 300)):
    sequence = books.loc[books["simple_categories"] == "Nonfiction", "description"].reset_index(drop=True)[i]
    predicted_cats += [generate_predictions(sequence, fiction_categories)]
    actual_cats += ["Nonfiction"]

100%|████████████████████████████████████████████████████████████████████████████████| 300/300 [03:26<00:00,  1.46it/s]

In [15]:
predictions_df = pd.DataFrame({"actual_categories": actual_cats, "predicted_categories": predicted_cats})

In [17]:
predictions_df["correct_prediction"]=(
    np.where(predictions_df["actual_categories"]==predictions_df["predicted_categories"],1,0)
)
predictions_df["correct_prediction"].sum()/len(predictions_df)

0.7783333333333333

In [19]:
isbns=[]
predicted_cats=[]
missing_cats=books.loc[books["simple_categories"].isna(),["isbn13","description"]].reset_index(drop=True)

In [20]:
for i in tqdm(range(0, len(missing_cats))):
    sequence=missing_cats["description"][i]
    predicted_cats+=[generate_predictions(sequence, fiction_categories)]
    isbns+=[missing_cats["isbn13"][i]]

100%|██████████████████████████████████████████████████████████████████████████████| 1454/1454 [16:14<00:00,  1.49it/s]

In [24]:
missing_predected_df= pd.DataFrame({"isbn13": isbns, "predicted_categories": predicted_cats})

In [26]:
books = pd.merge(books, missing_predected_df, on="isbn13", how="left")
books["simple_categories"] = np.where(books["simple_categories"].isna(), books["predicted_categories"], books["simple_categories"])
books = books.drop(columns = ["predicted_categories"])

In [27]:
books[books["categories"].str.lower().isin([
    "romance",
    "science fiction",
    "scifi",
    "fantasy",
    "horror",
    "mystery",
    "thriller",
    "comedy",
    "crime",
    "historical"
])]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,missing_desc,age_book,title_and_subtitle,tagged_description,simple_categories
24,9780006513087,0006513085,Gravity,Tess Gerritsen,Science fiction,http://books.google.com/books/content?id=KI66c...,Emma Watson a research physician has been trai...,2004.0,4.04,342.0,8024.0,1,22.0,Gravity,9780006513087 Emma Watson a research physician...,Nonfiction
475,9780099410355,0099410354,Traitor,Matthew Woodring Stover,Science fiction,http://books.google.com/books/content?id=VbICO...,"From the depths of catastrophe, a glimmer of h...",2002.0,4.00,320.0,6765.0,1,24.0,Traitor,"9780099410355 From the depths of catastrophe, ...",Fiction
478,9780099422341,0099422344,Yeats is Dead!,Joseph O'Connor,Comedy,http://books.google.com/books/content?id=DrE3I...,"In aid of Amnesty International, this is a bri...",2002.0,3.39,298.0,34.0,1,24.0,Yeats is Dead!: A Novel by Fifteen Irish Writers,"9780099422341 In aid of Amnesty International,...",Fiction
491,9780099446729,0099446723,Blackwood Farm,Anne Rice,Horror,http://books.google.com/books/content?id=cIn8T...,"Lestat Is Back, Saviour And Demon, Presiding O...",2003.0,3.86,774.0,26145.0,1,23.0,Blackwood Farm,"9780099446729 Lestat Is Back, Saviour And Demo...",Fiction
1090,9780261102422,0261102427,The Silmarillion,John Ronald Reuel Tolkien,Fantasy,http://books.google.com/books/content?id=22ePu...,Tolkien's Silmarillion is the core work of the...,1999.0,3.91,384.0,253.0,1,27.0,The Silmarillion,9780261102422 Tolkien's Silmarillion is the co...,Fiction
1435,9780340837955,0340837950,Stranger in a Strange Land,Robert A. Heinlein,Science fiction,http://books.google.com/books/content?id=ZQhiP...,"Epic, entertaining, Stranger in a Strange Land...",2005.0,3.92,672.0,563.0,1,21.0,Stranger in a Strange Land,"9780340837955 Epic, entertaining, Stranger in ...",Fiction
1439,9780345251220,0345251229,Visions from Nowhere,William Arrow,Science fiction,NaN,"The first novel in the series, ""Return to the ...",1976.0,3.23,183.0,10.0,1,50.0,Visions from Nowhere,"9780345251220 The first novel in the series, ""...",Fiction
2845,9780575075597,0575075597,Replay,Ken Grimwood,Fantasy,http://books.google.com/books/content?id=9vmNP...,At forty-three Jeff Winston is tired of his lo...,2005.0,4.16,272.0,412.0,1,21.0,Replay,9780575075597 At forty-three Jeff Winston is t...,Fiction
2860,9780590254762,0590254766,"The lion, the witch and the wardrobe",Clive Staples Lewis,Fantasy,NaN,Four English school children enter the magic l...,1995.0,4.21,189.0,860.0,1,31.0,"The lion, the witch and the wardrobe",9780590254762 Four English school children ent...,Nonfiction
3288,9780739423851,0739423851,Wizard's Castle,Diana Wynne Jones,Fantasy,http://books.google.com/books/content?id=hB7hA...,Howl's moving castle - Eldest of three sisters...,2002.0,4.44,376.0,439.0,1,24.0,Wizard's Castle,9780739423851 Howl's moving castle - Eldest of...,Fiction
3289,9780739439708,0739439707,Time Quartet,Madeleine L'Engle,Science fiction,NaN,"Blending magic with quantum physics, Madeleine...",2003.0,4.35,646.0,165.0,1,23.0,Time Quartet,9780739439708 Blending magic with quantum phys...,Fiction
3563,9780760728505,076072850X,"20,000 Leagues Under the Sea",Jules Verne,Science fiction,NaN,Retells the adventures of a French professor a...,2002.0,3.88,394.0,135778.0,1,24.0,"20,000 Leagues Under the Sea",9780760728505 Retells the adventures of a Fren...,Fiction
4483,9781416502043,1416502041,The Voyage of the Jerle Shannara Trilogy,Terry Brooks,Fantasy,http://books.google.com/books/content?id=jqVsA...,When the body of a half-drowned elf is found f...,2004.0,4.26,1260.0,84.0,1,22.0,The Voyage of the Jerle Shannara Trilogy,9781416502043 When the body of a half-drowned ...,Fiction
4979,9781841494081,1841494089,The Darkness that Comes Before,R. Scott Bakker,Fantasy,http://books.google.com/books/content?id=BG8qG...,A score of centuries has passed since the Firs...,2005.0,3.79,638.0,317.0,1,21.0,The Darkness that Comes Before,9781841494081 A score of centuries has passed ...,Nonfiction
5040,9781857231359,185723135X,Use of Weapons,Iain Banks,Science fiction,NaN,The man known as Cheradenine Zakalwe was one o...,1992.0,4.19,411.0,30779.0,1,34.0,Use of Weapons,9781857231359 The man known as Cheradenine Zak...,Nonfiction
5057,9781857989342,1857989341,The Gods Themselves,Isaac Asimov,Science fiction,http://books.google.com/books/content?id=8ClIP...,"In the year 2100, mankind on Earth, settlers i...",2000.0,4.09,288.0,41304.0,1,26.0,The Gods Themselves,"9781857989342 In the year 2100, mankind on Ear...",Fiction

In [28]:
books.to_csv("books_with_categories.csv", index=False)