In [2]:
!pip install -U \
  langchain-ollama \
  langchain-chroma \
  langchain-text-splitters \
  sentence-transformers \
  requests-toolbelt \
   "numpy<2"

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: langchain-ollama in c:\users\user\appdata\roaming\python\python312\site-packages (1.0.1)
Requirement already satisfied: langchain-chroma in c:\users\user\appdata\roaming\python\python312\site-packages (1.1.0)
Requirement already satisfied: langchain-text-splitters in c:\users\user\appdata\roaming\python\python312\site-packages (1.1.1)
Requirement already satisfied: sentence-transformers in c:\users\user\appdata\roaming\python\python312\site-packages (5.3.0)
Requirement already satisfied: requests-toolbelt in c:\programdata\anaconda3\lib\site-packages (1.0.0)
Requirement already satisfied: numpy<2 in c:\users\user\appdata\roaming\python\python312\site-packages (1.26.4)
Requirement already satisfied: langchain-core<2.0.0,>=1.0.0 in c:\users\user\appdata\roaming\python\python312\site-packages (from langchain-ollama) (1.2.20)
Requirement already satisfied: ollama<1.0.0,>=0.6.0 in c:\users\user\appdata\roaming\python\python312\site-packages (from langchain-ollama) (0.6.1)
Requirement already satisfied: chromadb<2.0.0,>=1.3.5 in c:\users\user\appdata\roaming\python\python312\site-packages (from langchain-chroma) (1.5.5)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in c:\users\user\appdata\roaming\python\python312\site-packages (from sentence-transformers) (4.57.1)
Requirement already satisfied: huggingface-hub>=0.20.0 in c:\users\user\appdata\roaming\python\python312\site-packages (from sentence-transformers) (0.36.0)
Requirement already satisfied: torch>=1.11.0 in c:\users\user\appdata\roaming\python\python312\site-packages (from sentence-transformers) (2.9.0)
Requirement already satisfied: scikit-learn in c:\programdata\anaconda3\lib\site-packages (from sentence-transformers) (1.5.1)
Requirement already satisfied: scipy in c:\programdata\anaconda3\lib\site-packages (from sentence-transformers) (1.13.1)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\user\appdata\roaming\python\python312\site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm in c:\programdata\anaconda3\lib\site-packages (from sentence-transformers) (4.66.5)
Requirement already satisfied: requests<3.0.0,>=2.0.1 in c:\users\user\appdata\roaming\python\python312\site-packages (from requests-toolbelt) (2.32.5)
Requirement already satisfied: build>=1.0.3 in c:\users\user\appdata\roaming\python\python312\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.4.0)
Requirement already satisfied: pydantic>=2.0 in c:\users\user\appdata\roaming\python\python312\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (2.12.3)
Requirement already satisfied: pydantic-settings>=2.0 in c:\users\user\appdata\roaming\python\python312\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (2.11.0)
Requirement already satisfied: pybase64>=1.4.1 in c:\users\user\appdata\roaming\python\python312\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.4.3)
Requirement already satisfied: uvicorn>=0.18.3 in c:\users\user\appdata\roaming\python\python312\site-packages (from uvicorn[standard]>=0.18.3->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.42.0)
Requirement already satisfied: onnxruntime>=1.14.1 in c:\users\user\appdata\roaming\python\python312\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.23.2)
Requirement already satisfied: opentelemetry-api>=1.2.0 in c:\users\user\appdata\roaming\python\python312\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.40.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc>=1.2.0 in c:\users\user\appdata\roaming\python\python312\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.40.0)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in c:\users\user\appdata\roaming\python\python312\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.40.0)
Requirement already satisfied: tokenizers>=0.13.2 in c:\users\user\appdata\roaming\python\python312\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.22.1)
Requirement already satisfied: pypika>=0.48.9 in c:\users\user\appdata\roaming\python\python312\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.51.1)
Requirement already satisfied: overrides>=7.3.1 in c:\programdata\anaconda3\lib\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (7.4.0)
Requirement already satisfied: importlib-resources in c:\users\user\appdata\roaming\python\python312\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (6.5.2)
Requirement already satisfied: grpcio>=1.58.0 in c:\users\user\appdata\roaming\python\python312\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.76.0)
Requirement already satisfied: bcrypt>=4.0.1 in c:\users\user\appdata\roaming\python\python312\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (5.0.0)
Requirement already satisfied: typer>=0.9.0 in c:\users\user\appdata\roaming\python\python312\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.24.1)
Requirement already satisfied: kubernetes>=28.1.0 in c:\users\user\appdata\roaming\python\python312\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (35.0.0)
Requirement already satisfied: tenacity>=8.2.3 in c:\programdata\anaconda3\lib\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (8.2.3)
Requirement already satisfied: pyyaml>=6.0.0 in c:\programdata\anaconda3\lib\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (6.0.1)
Requirement already satisfied: mmh3>=4.0.1 in c:\users\user\appdata\roaming\python\python312\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (5.2.1)
Requirement already satisfied: orjson>=3.9.12 in c:\users\user\appdata\roaming\python\python312\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (3.11.3)
Requirement already satisfied: httpx>=0.27.0 in c:\programdata\anaconda3\lib\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.27.0)
Requirement already satisfied: rich>=10.11.0 in c:\programdata\anaconda3\lib\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (13.7.1)
Requirement already satisfied: jsonschema>=4.19.0 in c:\programdata\anaconda3\lib\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (4.23.0)
Requirement already satisfied: filelock in c:\programdata\anaconda3\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\programdata\anaconda3\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2024.6.1)
Requirement already satisfied: packaging>=20.9 in c:\programdata\anaconda3\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (24.1)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in c:\programdata\anaconda3\lib\site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in c:\users\user\appdata\roaming\python\python312\site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.4.38)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in c:\users\user\appdata\roaming\python\python312\site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.14.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests<3.0.0,>=2.0.1->requests-toolbelt) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests<3.0.0,>=2.0.1->requests-toolbelt) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests<3.0.0,>=2.0.1->requests-toolbelt) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests<3.0.0,>=2.0.1->requests-toolbelt) (2024.8.30)
Requirement already satisfied: sympy>=1.13.3 in c:\users\user\appdata\roaming\python\python312\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\programdata\anaconda3\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.3)
Requirement already satisfied: jinja2 in c:\programdata\anaconda3\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.4)
Requirement already satisfied: setuptools in c:\programdata\anaconda3\lib\site-packages (from torch>=1.11.0->sentence-transformers) (75.1.0)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from tqdm->sentence-transformers) (0.4.6)
Requirement already satisfied: regex!=2019.12.17 in c:\programdata\anaconda3\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2024.9.11)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\user\appdata\roaming\python\python312\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.6.2)
Requirement already satisfied: joblib>=1.2.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn->sentence-transformers) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn->sentence-transformers) (3.5.0)
Requirement already satisfied: pyproject_hooks in c:\users\user\appdata\roaming\python\python312\site-packages (from build>=1.0.3->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.2.0)
Requirement already satisfied: anyio in c:\programdata\anaconda3\lib\site-packages (from httpx>=0.27.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (4.2.0)
Requirement already satisfied: httpcore==1.* in c:\users\user\appdata\roaming\python\python312\site-packages (from httpx>=0.27.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.0.9)
Requirement already satisfied: sniffio in c:\programdata\anaconda3\lib\site-packages (from httpx>=0.27.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.3.0)
Requirement already satisfied: h11>=0.16 in c:\users\user\appdata\roaming\python\python312\site-packages (from httpcore==1.*->httpx>=0.27.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in c:\programdata\anaconda3\lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (2.1)
Requirement already satisfied: attrs>=22.2.0 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=4.19.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=4.19.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=4.19.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=4.19.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.10.6)
Requirement already satisfied: six>=1.9.0 in c:\programdata\anaconda3\lib\site-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.16.0)
Requirement already satisfied: python-dateutil>=2.5.3 in c:\programdata\anaconda3\lib\site-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (2.9.0.post0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in c:\programdata\anaconda3\lib\site-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.8.0)
Requirement already satisfied: requests-oauthlib in c:\users\user\appdata\roaming\python\python312\site-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (2.0.0)
Requirement already satisfied: durationpy>=0.7 in c:\users\user\appdata\roaming\python\python312\site-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.10)
Requirement already satisfied: zstandard>=0.23.0 in c:\programdata\anaconda3\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.23.0)
Requirement already satisfied: coloredlogs in c:\users\user\appdata\roaming\python\python312\site-packages (from onnxruntime>=1.14.1->chromadb<2.0.0,>=1.3.5->langchain-chroma) (15.0.1)
Requirement already satisfied: flatbuffers in c:\users\user\appdata\roaming\python\python312\site-packages (from onnxruntime>=1.14.1->chromadb<2.0.0,>=1.3.5->langchain-chroma) (25.9.23)
Requirement already satisfied: protobuf in c:\users\user\appdata\roaming\python\python312\site-packages (from onnxruntime>=1.14.1->chromadb<2.0.0,>=1.3.5->langchain-chroma) (6.33.0)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in c:\programdata\anaconda3\lib\site-packages (from opentelemetry-api>=1.2.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (7.0.1)
Requirement already satisfied: googleapis-common-protos~=1.57 in c:\users\user\appdata\roaming\python\python312\site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.71.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.40.0 in c:\users\user\appdata\roaming\python\python312\site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.40.0)
Requirement already satisfied: opentelemetry-proto==1.40.0 in c:\users\user\appdata\roaming\python\python312\site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.40.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.61b0 in c:\users\user\appdata\roaming\python\python312\site-packages (from opentelemetry-sdk>=1.2.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.61b0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\programdata\anaconda3\lib\site-packages (from pydantic>=2.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.4 in c:\users\user\appdata\roaming\python\python312\site-packages (from pydantic>=2.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\user\appdata\roaming\python\python312\site-packages (from pydantic>=2.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in c:\programdata\anaconda3\lib\site-packages (from pydantic-settings>=2.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.21.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\programdata\anaconda3\lib\site-packages (from rich>=10.11.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\programdata\anaconda3\lib\site-packages (from rich>=10.11.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (2.15.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\programdata\anaconda3\lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: click>=8.2.1 in c:\users\user\appdata\roaming\python\python312\site-packages (from typer>=0.9.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\user\appdata\roaming\python\python312\site-packages (from typer>=0.9.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\user\appdata\roaming\python\python312\site-packages (from typer>=0.9.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.0.4)
Requirement already satisfied: httptools>=0.6.3 in c:\users\user\appdata\roaming\python\python312\site-packages (from uvicorn[standard]>=0.18.3->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.7.1)
Requirement already satisfied: watchfiles>=0.20 in c:\users\user\appdata\roaming\python\python312\site-packages (from uvicorn[standard]>=0.18.3->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.1.1)
Requirement already satisfied: websockets>=10.4 in c:\users\user\appdata\roaming\python\python312\site-packages (from uvicorn[standard]>=0.18.3->chromadb<2.0.0,>=1.3.5->langchain-chroma) (16.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\programdata\anaconda3\lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (2.1.3)
Requirement already satisfied: zipp>=0.5 in c:\programdata\anaconda3\lib\site-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api>=1.2.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (3.17.0)
Requirement already satisfied: mdurl~=0.1 in c:\programdata\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.1.0)
Requirement already satisfied: humanfriendly>=9.1 in c:\users\user\appdata\roaming\python\python312\site-packages (from coloredlogs->onnxruntime>=1.14.1->chromadb<2.0.0,>=1.3.5->langchain-chroma) (10.0)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\user\appdata\roaming\python\python312\site-packages (from requests-oauthlib->kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (3.3.1)
Requirement already satisfied: pyreadline3 in c:\users\user\appdata\roaming\python\python312\site-packages (from humanfriendly>=9.1->coloredlogs->onnxruntime>=1.14.1->chromadb<2.0.0,>=1.3.5->langchain-chroma) (3.5.4)

In [3]:
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_ollama import OllamaEmbeddings
from langchain_chroma import Chroma

In [4]:
import pandas as pd

books=pd.read_csv("books_cleaned.csv")

In [9]:

embeddings = OllamaEmbeddings(model="nomic-embed-text:latest")

In [18]:
books["tagged_description"].to_csv("target_description.txt", sep="\n", index=False,header=False, encoding="utf-8")

In [11]:
import os

# Check current working directory
cwd = os.getcwd()
print(f"📂 Current Directory: {cwd}")

# Check if the file is in this directory
files = os.listdir(cwd)
if "target_description.txt" in files:
    print("✅ Found it! It's right here.")
else:
    print("❌ Not found in this folder. Here's what I DO see:")
    print(files[:10])

📂 Current Directory: C:\Users\user
✅ Found it! It's right here.

In [6]:
from langchain_community.document_loaders import TextLoader

loader = TextLoader("target_description.txt", encoding="utf-8")
raw_documents = loader.load()

In [7]:
from langchain_text_splitters import CharacterTextSplitter

# Use a chunk_size that fits your data (e.g., 500 characters)
text_splitter = CharacterTextSplitter(
    separator="\n",
    chunk_size=500,        # Must be > 0
    chunk_overlap=0,       # Set to 0 if you want clean breaks
    is_separator_regex=False
)

documents = text_splitter.split_documents(raw_documents)
print(f"✅ Created {len(documents)} chunks by splitting at \\n.")

Created a chunk of size 1168, which is longer than the specified 500
Created a chunk of size 1214, which is longer than the specified 500
Created a chunk of size 960, which is longer than the specified 500
Created a chunk of size 843, which is longer than the specified 500
Created a chunk of size 881, which is longer than the specified 500
Created a chunk of size 1088, which is longer than the specified 500
Created a chunk of size 1189, which is longer than the specified 500
Created a chunk of size 513, which is longer than the specified 500
Created a chunk of size 752, which is longer than the specified 500
Created a chunk of size 728, which is longer than the specified 500
Created a chunk of size 721, which is longer than the specified 500
Created a chunk of size 1267, which is longer than the specified 500
Created a chunk of size 681, which is longer than the specified 500
Created a chunk of size 553, which is longer than the specified 500
Created a chunk of size 521, which is longer than the specified 500
Created a chunk of size 787, which is longer than the specified 500
Created a chunk of size 564, which is longer than the specified 500
Created a chunk of size 523, which is longer than the specified 500
Created a chunk of size 533, which is longer than the specified 500
Created a chunk of size 559, which is longer than the specified 500
Created a chunk of size 563, which is longer than the specified 500
Created a chunk of size 595, which is longer than the specified 500
Created a chunk of size 614, which is longer than the specified 500
Created a chunk of size 887, which is longer than the specified 500
Created a chunk of size 693, which is longer than the specified 500
Created a chunk of size 2010, which is longer than the specified 500
Created a chunk of size 520, which is longer than the specified 500
Created a chunk of size 647, which is longer than the specified 500
Created a chunk of size 778, which is longer than the specified 500
Created a chunk of size 686, which is longer than the specified 500
Created a chunk of size 548, which is longer than the specified 500
Created a chunk of size 1225, which is longer than the specified 500
Created a chunk of size 1184, which is longer than the specified 500
Created a chunk of size 1214, which is longer than the specified 500
Created a chunk of size 1191, which is longer than the specified 500
Created a chunk of size 1057, which is longer than the specified 500
Created a chunk of size 688, which is longer than the specified 500
Created a chunk of size 876, which is longer than the specified 500
Created a chunk of size 766, which is longer than the specified 500
Created a chunk of size 723, which is longer than the specified 500
Created a chunk of size 526, which is longer than the specified 500
Created a chunk of size 521, which is longer than the specified 500
Created a chunk of size 899, which is longer than the specified 500
Created a chunk of size 1270, which is longer than the specified 500
Created a chunk of size 558, which is longer than the specified 500
Created a chunk of size 1635, which is longer than the specified 500
Created a chunk of size 777, which is longer than the specified 500
Created a chunk of size 716, which is longer than the specified 500
Created a chunk of size 514, which is longer than the specified 500
Created a chunk of size 958, which is longer than the specified 500
Created a chunk of size 1132, which is longer than the specified 500
Created a chunk of size 1325, which is longer than the specified 500
Created a chunk of size 851, which is longer than the specified 500
Created a chunk of size 801, which is longer than the specified 500
Created a chunk of size 1119, which is longer than the specified 500
Created a chunk of size 836, which is longer than the specified 500
Created a chunk of size 732, which is longer than the specified 500
Created a chunk of size 1195, which is longer than the specified 500
Created a chunk of size 710, which is longer than the specified 500
Created a chunk of size 773, which is longer than the specified 500
Created a chunk of size 766, which is longer than the specified 500
Created a chunk of size 767, which is longer than the specified 500
Created a chunk of size 716, which is longer than the specified 500
Created a chunk of size 2012, which is longer than the specified 500
Created a chunk of size 1286, which is longer than the specified 500
Created a chunk of size 1231, which is longer than the specified 500
Created a chunk of size 729, which is longer than the specified 500
Created a chunk of size 750, which is longer than the specified 500
Created a chunk of size 1242, which is longer than the specified 500
Created a chunk of size 912, which is longer than the specified 500
Created a chunk of size 844, which is longer than the specified 500
Created a chunk of size 1126, which is longer than the specified 500
Created a chunk of size 1073, which is longer than the specified 500
Created a chunk of size 1318, which is longer than the specified 500
Created a chunk of size 2834, which is longer than the specified 500
Created a chunk of size 570, which is longer than the specified 500
Created a chunk of size 1141, which is longer than the specified 500
Created a chunk of size 1004, which is longer than the specified 500
Created a chunk of size 715, which is longer than the specified 500
Created a chunk of size 710, which is longer than the specified 500
Created a chunk of size 2510, which is longer than the specified 500
Created a chunk of size 954, which is longer than the specified 500
Created a chunk of size 639, which is longer than the specified 500
Created a chunk of size 523, which is longer than the specified 500
Created a chunk of size 793, which is longer than the specified 500
Created a chunk of size 1422, which is longer than the specified 500
Created a chunk of size 1083, which is longer than the specified 500
Created a chunk of size 1144, which is longer than the specified 500
Created a chunk of size 1268, which is longer than the specified 500
Created a chunk of size 790, which is longer than the specified 500
Created a chunk of size 1086, which is longer than the specified 500
Created a chunk of size 874, which is longer than the specified 500
Created a chunk of size 876, which is longer than the specified 500
Created a chunk of size 806, which is longer than the specified 500
Created a chunk of size 1812, which is longer than the specified 500
Created a chunk of size 1830, which is longer than the specified 500
Created a chunk of size 1064, which is longer than the specified 500
Created a chunk of size 955, which is longer than the specified 500
Created a chunk of size 1180, which is longer than the specified 500
Created a chunk of size 1284, which is longer than the specified 500
Created a chunk of size 1642, which is longer than the specified 500
Created a chunk of size 757, which is longer than the specified 500
Created a chunk of size 1930, which is longer than the specified 500
Created a chunk of size 872, which is longer than the specified 500
Created a chunk of size 2008, which is longer than the specified 500
Created a chunk of size 2285, which is longer than the specified 500
Created a chunk of size 1003, which is longer than the specified 500
Created a chunk of size 577, which is longer than the specified 500
Created a chunk of size 1142, which is longer than the specified 500
Created a chunk of size 557, which is longer than the specified 500
Created a chunk of size 1143, which is longer than the specified 500
Created a chunk of size 1086, which is longer than the specified 500
Created a chunk of size 1483, which is longer than the specified 500
Created a chunk of size 1135, which is longer than the specified 500
Created a chunk of size 722, which is longer than the specified 500
Created a chunk of size 668, which is longer than the specified 500
Created a chunk of size 765, which is longer than the specified 500
Created a chunk of size 606, which is longer than the specified 500
Created a chunk of size 570, which is longer than the specified 500
Created a chunk of size 965, which is longer than the specified 500
Created a chunk of size 857, which is longer than the specified 500
Created a chunk of size 1032, which is longer than the specified 500
Created a chunk of size 652, which is longer than the specified 500
Created a chunk of size 733, which is longer than the specified 500
Created a chunk of size 525, which is longer than the specified 500
Created a chunk of size 1015, which is longer than the specified 500
Created a chunk of size 970, which is longer than the specified 500
Created a chunk of size 688, which is longer than the specified 500
Created a chunk of size 544, which is longer than the specified 500
Created a chunk of size 931, which is longer than the specified 500
Created a chunk of size 564, which is longer than the specified 500
Created a chunk of size 854, which is longer than the specified 500
Created a chunk of size 715, which is longer than the specified 500
Created a chunk of size 749, which is longer than the specified 500
Created a chunk of size 712, which is longer than the specified 500
Created a chunk of size 1088, which is longer than the specified 500
Created a chunk of size 723, which is longer than the specified 500
Created a chunk of size 704, which is longer than the specified 500
Created a chunk of size 1912, which is longer than the specified 500
Created a chunk of size 622, which is longer than the specified 500
Created a chunk of size 559, which is longer than the specified 500
Created a chunk of size 556, which is longer than the specified 500
Created a chunk of size 624, which is longer than the specified 500
Created a chunk of size 2616, which is longer than the specified 500
Created a chunk of size 1580, which is longer than the specified 500
Created a chunk of size 994, which is longer than the specified 500
Created a chunk of size 847, which is longer than the specified 500
Created a chunk of size 1530, which is longer than the specified 500
Created a chunk of size 2030, which is longer than the specified 500
Created a chunk of size 1619, which is longer than the specified 500
Created a chunk of size 698, which is longer than the specified 500
Created a chunk of size 822, which is longer than the specified 500
Created a chunk of size 843, which is longer than the specified 500
Created a chunk of size 1189, which is longer than the specified 500
Created a chunk of size 508, which is longer than the specified 500
Created a chunk of size 663, which is longer than the specified 500
Created a chunk of size 1282, which is longer than the specified 500
Created a chunk of size 1268, which is longer than the specified 500
Created a chunk of size 1277, which is longer than the specified 500
Created a chunk of size 1056, which is longer than the specified 500
Created a chunk of size 784, which is longer than the specified 500
Created a chunk of size 969, which is longer than the specified 500
Created a chunk of size 613, which is longer than the specified 500
Created a chunk of size 757, which is longer than the specified 500
Created a chunk of size 963, which is longer than the specified 500
Created a chunk of size 843, which is longer than the specified 500
Created a chunk of size 786, which is longer than the specified 500
Created a chunk of size 648, which is longer than the specified 500
Created a chunk of size 984, which is longer than the specified 500
Created a chunk of size 799, which is longer than the specified 500
Created a chunk of size 1163, which is longer than the specified 500
Created a chunk of size 1058, which is longer than the specified 500
Created a chunk of size 875, which is longer than the specified 500
Created a chunk of size 817, which is longer than the specified 500
Created a chunk of size 755, which is longer than the specified 500
Created a chunk of size 569, which is longer than the specified 500
Created a chunk of size 628, which is longer than the specified 500
Created a chunk of size 868, which is longer than the specified 500
Created a chunk of size 620, which is longer than the specified 500
Created a chunk of size 621, which is longer than the specified 500
Created a chunk of size 1084, which is longer than the specified 500
Created a chunk of size 2762, which is longer than the specified 500
Created a chunk of size 1033, which is longer than the specified 500
Created a chunk of size 758, which is longer than the specified 500
Created a chunk of size 773, which is longer than the specified 500
Created a chunk of size 634, which is longer than the specified 500
Created a chunk of size 1010, which is longer than the specified 500
Created a chunk of size 1064, which is longer than the specified 500
Created a chunk of size 795, which is longer than the specified 500
Created a chunk of size 699, which is longer than the specified 500
Created a chunk of size 1224, which is longer than the specified 500
Created a chunk of size 657, which is longer than the specified 500
Created a chunk of size 767, which is longer than the specified 500
Created a chunk of size 553, which is longer than the specified 500
Created a chunk of size 590, which is longer than the specified 500
Created a chunk of size 726, which is longer than the specified 500
Created a chunk of size 1805, which is longer than the specified 500
Created a chunk of size 1017, which is longer than the specified 500
Created a chunk of size 684, which is longer than the specified 500
Created a chunk of size 739, which is longer than the specified 500
Created a chunk of size 922, which is longer than the specified 500
Created a chunk of size 967, which is longer than the specified 500
Created a chunk of size 645, which is longer than the specified 500
Created a chunk of size 676, which is longer than the specified 500
Created a chunk of size 712, which is longer than the specified 500
Created a chunk of size 799, which is longer than the specified 500
Created a chunk of size 854, which is longer than the specified 500
Created a chunk of size 670, which is longer than the specified 500
Created a chunk of size 854, which is longer than the specified 500
Created a chunk of size 760, which is longer than the specified 500
Created a chunk of size 796, which is longer than the specified 500
Created a chunk of size 679, which is longer than the specified 500
Created a chunk of size 927, which is longer than the specified 500
Created a chunk of size 1268, which is longer than the specified 500
Created a chunk of size 733, which is longer than the specified 500
Created a chunk of size 868, which is longer than the specified 500
Created a chunk of size 931, which is longer than the specified 500
Created a chunk of size 772, which is longer than the specified 500
Created a chunk of size 770, which is longer than the specified 500
Created a chunk of size 649, which is longer than the specified 500
Created a chunk of size 1771, which is longer than the specified 500
Created a chunk of size 534, which is longer than the specified 500
Created a chunk of size 824, which is longer than the specified 500
Created a chunk of size 599, which is longer than the specified 500
Created a chunk of size 969, which is longer than the specified 500
Created a chunk of size 554, which is longer than the specified 500
Created a chunk of size 844, which is longer than the specified 500
Created a chunk of size 876, which is longer than the specified 500
Created a chunk of size 670, which is longer than the specified 500
Created a chunk of size 707, which is longer than the specified 500
Created a chunk of size 654, which is longer than the specified 500
Created a chunk of size 1270, which is longer than the specified 500
Created a chunk of size 736, which is longer than the specified 500
Created a chunk of size 1019, which is longer than the specified 500
Created a chunk of size 777, which is longer than the specified 500
Created a chunk of size 682, which is longer than the specified 500
Created a chunk of size 598, which is longer than the specified 500
Created a chunk of size 663, which is longer than the specified 500
Created a chunk of size 595, which is longer than the specified 500
Created a chunk of size 857, which is longer than the specified 500
Created a chunk of size 595, which is longer than the specified 500
Created a chunk of size 537, which is longer than the specified 500
Created a chunk of size 567, which is longer than the specified 500
Created a chunk of size 705, which is longer than the specified 500
Created a chunk of size 848, which is longer than the specified 500
Created a chunk of size 542, which is longer than the specified 500
Created a chunk of size 1177, which is longer than the specified 500
Created a chunk of size 904, which is longer than the specified 500
Created a chunk of size 852, which is longer than the specified 500
Created a chunk of size 507, which is longer than the specified 500
Created a chunk of size 1715, which is longer than the specified 500
Created a chunk of size 845, which is longer than the specified 500
Created a chunk of size 1681, which is longer than the specified 500
Created a chunk of size 721, which is longer than the specified 500
Created a chunk of size 659, which is longer than the specified 500
Created a chunk of size 603, which is longer than the specified 500
Created a chunk of size 991, which is longer than the specified 500
Created a chunk of size 1128, which is longer than the specified 500
Created a chunk of size 2005, which is longer than the specified 500
Created a chunk of size 1171, which is longer than the specified 500
Created a chunk of size 2141, which is longer than the specified 500
Created a chunk of size 662, which is longer than the specified 500
Created a chunk of size 1322, which is longer than the specified 500
Created a chunk of size 526, which is longer than the specified 500
Created a chunk of size 1112, which is longer than the specified 500
Created a chunk of size 664, which is longer than the specified 500
Created a chunk of size 908, which is longer than the specified 500
Created a chunk of size 1316, which is longer than the specified 500
Created a chunk of size 691, which is longer than the specified 500
Created a chunk of size 950, which is longer than the specified 500
Created a chunk of size 1121, which is longer than the specified 500
Created a chunk of size 776, which is longer than the specified 500
Created a chunk of size 615, which is longer than the specified 500
Created a chunk of size 533, which is longer than the specified 500
Created a chunk of size 1018, which is longer than the specified 500
Created a chunk of size 725, which is longer than the specified 500
Created a chunk of size 612, which is longer than the specified 500
Created a chunk of size 629, which is longer than the specified 500
Created a chunk of size 1007, which is longer than the specified 500
Created a chunk of size 616, which is longer than the specified 500
Created a chunk of size 884, which is longer than the specified 500
Created a chunk of size 579, which is longer than the specified 500
Created a chunk of size 911, which is longer than the specified 500
Created a chunk of size 1057, which is longer than the specified 500
Created a chunk of size 630, which is longer than the specified 500
Created a chunk of size 1255, which is longer than the specified 500
Created a chunk of size 572, which is longer than the specified 500
Created a chunk of size 1098, which is longer than the specified 500
Created a chunk of size 907, which is longer than the specified 500
Created a chunk of size 621, which is longer than the specified 500
Created a chunk of size 877, which is longer than the specified 500
Created a chunk of size 1143, which is longer than the specified 500

✅ Created 4415 chunks by splitting at \n.

In [8]:
documents[1]

Document(metadata={'source': 'target_description.txt'}, page_content="9780002261982 A new 'Christie for Christmas' -- a full-length novel adapted from her acclaimed play by Charles Osborne Following BLACK COFFEE and THE UNEXPECTED GUEST comes the final Agatha Christie play novelisation, bringing her superb storytelling to a new legion of fans. Clarissa, the wife of a Foreign Office diplomat, is given to daydreaming. 'Supposing I were to come down one morning and find a dead body in the library, what should I do?' she muses. Clarissa has her chance to find out when she discovers a body in the drawing-room of her house in Kent. Desperate to dispose of the body before her husband comes home with an important foreign politician, Clarissa persuades her three house guests to become accessories and accomplices. It seems that the murdered man was not unknown to certain members of the house party (but which ones?), and the search begins for the murderer and the motive, while at the same time trying to persuade a police inspector that there has been no murder at all... SPIDER'S WEB was written in 1954 specifically for Margaret Lockwood and opened first at the Theatre Royal Nottingham before moving to the Savoy Theatre in London on 14 December 1954. With THE MOUSETRAP and WI")

In [10]:
db_books= Chroma.from_documents(
    documents,
    embedding=embeddings
)

In [11]:
query = "A book to teach children about nature"
docs = db_books.similarity_search(query, k = 10)
docs

[Document(id='1d40032f-8555-43ae-9f39-77fb78ed0a05', metadata={'source': 'target_description.txt'}, page_content='9780786808069 Children will discover the exciting world of their own backyard in this introduction to familiar animals from cats and dogs to bugs and frogs. The combination of photographs, illustrations, and fun facts make this an accessible and delightful learning experience.'),
 Document(id='451b79a3-b3a4-44bb-b716-494c7d37b9d1', metadata={'source': 'target_description.txt'}, page_content="9780786808380 Introduce your babies to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing the baby to some basic -- and sometimes playful -- information about the subjects."),
 Document(id='c79efdd5-ca65-433f-b759-a606912ba60c', metadata={'source': 'target_description.txt'}, page_content="9780786808373 Introducing your baby to birds, cats, dogs, and babies through fine art, illsutration and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information on the subjects."),
 Document(id='3c27b3d3-7419-418c-942a-cd73f12d89d6', metadata={'source': 'target_description.txt'}, page_content="9780786808397 Introduce your baby to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to exopse little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information about the subjects."),
 Document(id='38cc6a33-86ae-4b87-9d56-49290d801a77', metadata={'source': 'target_description.txt'}, page_content='9780898599596 This is a book about how we see: the environment around us (its surfaces, their layout, and their colors and textures); where we are in the environment; whether or not we are moving and, if we are, where we are going; what things are good for; how to do things (to thread a needle or drive an automobile); or why things look as they do. The basic assumption is that vision depends on the eye which is connected to the brain. The author suggests that natural vision depends on the eyes in the head on a body supported by the ground, the brain being only the central organ of a complete visual system. When no constraints are put on the visual system, people look around, walk up to something interesting and move around it so as to see it from all sides, and go from one vista to another. That is natural vision -- and what this book is about.'),
 Document(id='10620f02-679d-40a3-ac63-98bf3d911e51', metadata={'source': 'target_description.txt'}, page_content="9780131871656 This introduction to astronomy features an exceptionally clear writing style, an emphasis on critical thinking and visualization, and a leading-edge technology program-including an accompanying full-featured electronic multimedia version of the book and companion Web site. A dynamic art program includes numerous radio, infrared, ultraviolet, X-ray, and gamma-ray images and transparent full-color overlays. The book presents scientific literacy in the context of astronomy, with the aim of teaching studentsto think critically and analytically about the physical world and the development of science. The text requires a minimum level of simple algebra and trigonometry. It presents an explanation of key physical principles and techniques like Kepler and Newton's laws, spectroscopy and distance measurement (the cosmic distance ladder is used throughout)."),
 Document(id='95112db5-db06-4a76-b0a0-d06a33ba7164', metadata={'source': 'target_description.txt'}, page_content="9780941807555 THE LITTLE BIG BOOK FOR GOD'S CHILDREN is a wonderful resource for parents looking to introduce their children to the wisdom and beauty of Christian faith. Illustrated with early twentieth-century art from artists such as Jessie Wilcox Smith, Ellen H. Clapsaddle, and Maud and Miska Petersham, this Little Big Book presents selected bible stories, parables, and verses; poems and prayers; excerpts and fables; songs and hymns; and activities - all collected in one delightful volume. A celebration of God's enduring message of love, GOD'S CHILDREN is sure to provide an endless wellspring of inspiration and hope."),
 Document(id='46a42891-2e20-4104-ab49-693795064ec2', metadata={'source': 'target_description.txt'}, page_content="9780374522599 The Control of Nature is John McPhee's bestselling account of places where people are locked in combat with nature. Taking us deep into these contested territories, McPhee details the strageties and tactics through which people attempt to control nature. Most striking is his depiction of the main contestants: nature in complex and awesome guises, and those attempting to wrest control from her - stubborn, sometimes foolhardy, more often ingenious, and always arresting characters."),
 Document(id='e6a97390-cb4d-446a-8a55-c1f66724a045', metadata={'source': 'target_description.txt'}, page_content="9780064405959 When seven Siberian snow spiders, frozen during the Ice Age, defrost and escape en route to Harvard for analysis, they wreak havoc on a small New England town, disrupting the school Halloween pageant with hilarious results. An ALA Notable Children's Book. Reissue."),
 Document(id='776c796c-5fa6-4e8a-a029-72e40b5a1199', metadata={'source': 'target_description.txt'}, page_content='"9780067575208 First published more than three decades ago, this reissue of Rachel Carson\'s award-winning classic brings her unique vision to a new generation of readers. Stunning new photographs by Nick Kelsh beautifully complement Carson\'s intimate account of adventures with her young nephew, Roger, as they enjoy walks along the rocky coast of Maine and through dense forests and open fields, observing wildlife, strange plants, moonlight and storm clouds, and listening to the ""living music"" of insects in the underbrush. ""If a child is to keep alive his inborn sense of wonder."" Writes Carson, ""he needs the companionship of at least one adult who can share it, rediscovering with him the joy, excitement and mystery of the world we live in."" The Sense of Wonder is a refreshing antidote to indifference and a guide to capturing the simple power of discovery that Carson views as essential to life. In her insightful new introduction, Linda Lear remembers Rachel Carson\'s groundbreaking achievements in the context of the legendary environmentalist\'s personal commitment to introducing young and old to the miracles of nature. Kelsh\'s lush photographs inspire sensual, tactile reactions: masses of leaves floating in a puddle are just waiting to be scooped up and examined more closely. An image of a narrow path through the trees evokes the earthy scent of the woods after a summer rain. Close-ups of mosses and miniature lichen fantasy-lands will spark innocent\'as well as more jaded\'imaginations. Like a curious child studying things underfoot and within reach, Kelsh\'s camera is drawn to patterns in nature that too often elude hurried adults\'a stand of beech trees in the springtime, patches of melting snow and the ripples from a pebble tossed into a slow-moving stream. The Sense of Wonder is a timeless volume that will be passed on from children to grandchildren, as treasured as the memory of an early-morning walk when the song of a whippoorwill was heard as if for the first time."')]

In [12]:
books[books["isbn13"] == int(docs[0].page_content.split()[0].strip())]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,missing_desc,age_book,title_and_subtitle,tagged_description
3747,9780786808069,0786808063,Baby Einstein: Neighborhood Animals,Marilyn Singer;Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=X9a4P...,Children will discover the exciting world of t...,2001.0,3.89,16.0,180.0,1,25.0,Baby Einstein: Neighborhood Animals,9780786808069 Children will discover the excit...

In [13]:
def retrieve_semantic_recommendations(
        query: str,
        top_k: int = 10,
) -> pd.DataFrame:
    recs = db_books.similarity_search(query, k = 50)

    books_list = []

    for i in range(0, len(recs)):
        books_list += [int(recs[i].page_content.strip('"').split()[0])]

    return books[books["isbn13"].isin(books_list)]

In [14]:
retrieve_semantic_recommendations("A book to teach children about nature")

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,missing_desc,age_book,title_and_subtitle,tagged_description
59,9780007151240,0007151241,The Family Way,Tony Parsons,Parenthood,http://books.google.com/books/content?id=dJEIx...,It should be the most natural thing in the wor...,2005.0,3.51,400.0,2095.0,1,21.0,The Family Way,9780007151240 It should be the most natural th...
143,9780060546571,0060546573,Three Rotten Eggs,Gregory Maguire,Juvenile Fiction,http://books.google.com/books/content?id=t2pWl...,The students of Miss Earth's class in rural Ve...,2005.0,3.74,240.0,76.0,1,21.0,Three Rotten Eggs,9780060546571 The students of Miss Earth's cla...
146,9780060556501,0060556501,"The Lion, the Witch and the Wardrobe (picture ...",C. S. Lewis,Juvenile Fiction,http://books.google.com/books/content?id=FlSpp...,Narnia: A magical land full of wonder and exci...,2004.0,4.19,48.0,5012.0,1,22.0,"The Lion, the Witch and the Wardrobe (picture ...",9780060556501 Narnia: A magical land full of w...
414,9780064405959,0064405958,Seven Spiders Spinning,Gregory Maguire,Juvenile Fiction,http://books.google.com/books/content?id=VPf_u...,"When seven Siberian snow spiders, frozen durin...",1995.0,3.61,144.0,259.0,1,31.0,Seven Spiders Spinning,9780064405959 When seven Siberian snow spiders...
429,9780064434980,0064434982,The Deer in the Wood,Laura Ingalls Wilder,Juvenile Fiction,http://books.google.com/books/content?id=V7YDW...,Even the youngest child can enjoy a special ad...,1999.0,4.17,32.0,302.0,1,27.0,The Deer in the Wood,9780064434980 Even the youngest child can enjo...
436,9780064471961,0064471969,Shade's Children (rack),Garth Nix,Juvenile Fiction,http://books.google.com/books/content?id=_jlgl...,The Key to Survival Rests in the Hands of Shad...,1998.0,3.90,345.0,10368.0,1,28.0,Shade's Children (rack),9780064471961 The Key to Survival Rests in the...
442,9780067575208,006757520X,The Sense of Wonder,Rachel Carson,Nature,http://books.google.com/books/content?id=Zee5S...,"First published more than three decades ago, t...",1998.0,4.39,112.0,1160.0,1,28.0,The Sense of Wonder,9780067575208 First published more than three ...
549,9780131871656,013187165X,Astronomy,Eric Chaisson;Stephen McMillan,Mathematics,http://books.google.com/books/content?id=1O00A...,This introduction to astronomy features an exc...,2006.0,3.85,499.0,153.0,1,20.0,Astronomy: a beginner's guide to the universe,9780131871656 This introduction to astronomy f...
568,9780140139976,0140139974,Sailor Song,Ken Kesey,Fiction,http://books.google.com/books/content?id=-pPSO...,"In Alaska to film a famous children's book, th...",1993.0,3.57,533.0,1956.0,1,33.0,Sailor Song,9780140139976 In Alaska to film a famous child...
706,9780140503449,0140503447,Christmas in Noisy Village,Astrid Lindgren;Ilon Wikland,Juvenile Fiction,http://books.google.com/books/content?id=blqrN...,The noisy children of three neighboring famili...,1981.0,4.18,32.0,797.0,1,45.0,Christmas in Noisy Village,9780140503449 The noisy children of three neig...
815,9780142402498,0142402494,Pippi Longstocking,Astrid Lindgren,Juvenile Fiction,http://books.google.com/books/content?id=STE5P...,Relates the antics of a rambunctious girl who ...,2005.0,4.12,160.0,140107.0,1,21.0,Pippi Longstocking,9780142402498 Relates the antics of a rambunct...
819,9780142404201,0142404209,Charlie and the Chocolate Factory,Roald Dahl,Juvenile Fiction,http://books.google.com/books/content?id=X73lH...,Each of five children lucky enough to discover...,2005.0,3.86,40.0,12.0,1,21.0,Charlie and the Chocolate Factory,9780142404201 Each of five children lucky enou...
833,9780142500378,0142500372,Enchantress from the Stars,Sylvia Louise Engdahl,Juvenile Fiction,http://books.google.com/books/content?id=rntJA...,When young Elana unexpectedly joins the team l...,2003.0,3.94,304.0,2031.0,1,23.0,Enchantress from the Stars,9780142500378 When young Elana unexpectedly jo...
1638,9780374299194,0374299196,The Discomfort Zone,Jonathan Franzen,Biography & Autobiography,http://books.google.com/books/content?id=Z2vOA...,The author describes growing up in a family of...,2006.0,3.39,195.0,4660.0,1,20.0,The Discomfort Zone: A Personal History,9780374299194 The author describes growing up ...
1639,9780374422080,0374422087,Everything on a Waffle,Polly Horvath,Juvenile Fiction,http://books.google.com/books/content?id=NimVJ...,This Newbery Honor Book tells the story of 11 ...,2004.0,3.71,150.0,9631.0,1,22.0,Everything on a Waffle,9780374422080 This Newbery Honor Book tells th...
1642,9780374522599,0374522596,The Control of Nature,John McPhee,Nature,http://books.google.com/books/content?id=p1qKQ...,The Control of Nature is John McPhee's bestsel...,1990.0,4.24,288.0,3365.0,1,36.0,The Control of Nature,9780374522599 The Control of Nature is John Mc...
1734,9780375760396,0375760393,The Botany of Desire,Michael Pollan,Gardening,http://books.google.com/books/content?id=tsx9x...,Focusing on the human relationship with plants...,2001.0,4.06,297.0,39426.0,1,25.0,The Botany of Desire: A Plant's-eye View of th...,9780375760396 Focusing on the human relationsh...
1880,9780385732550,0385732554,The Giver,Lois Lowry,Juvenile Fiction,http://books.google.com/books/content?id=oZRlY...,"At the age of twelve, Jonas, a young boy from ...",2006.0,4.12,208.0,1464909.0,1,20.0,The Giver,"9780385732550 At the age of twelve, Jonas, a y..."
2126,9780439569729,0439569729,SCHOLASTIC SUCCESS WITH 4TH GRADE(WORKBOOK),Terry Cooper,Education,http://books.google.com/books/content?id=b-EBH...,"416 bright, colorful pages that give kids prac...",2003.0,4.57,416.0,7.0,1,23.0,SCHOLASTIC SUCCESS WITH 4TH GRADE(WORKBOOK),"9780439569729 416 bright, colorful pages that ..."
2164,9780439994798,0439994799,His Dark Materials,Philip Pullman,"Children's stories, English",http://books.google.com/books/content?id=E9ZkG...,The trilogy follows the coming of age of two c...,2001.0,4.26,1296.0,304.0,1,25.0,His Dark Materials,9780439994798 The trilogy follows the coming o...
2718,9780553382617,0553382616,The Shelters of Stone,Jean M. Auel,Fiction,http://books.google.com/books/content?id=BmAgt...,In the fifth volume of the best-selling Earth'...,2004.0,3.82,891.0,33918.0,1,22.0,The Shelters of Stone,9780553382617 In the fifth volume of the best-...
2805,9780571084838,0571084834,Lord of the Flies,William Golding,Airplane crash survival,NaN,After a plane crash strands them on a tropical...,1954.0,3.67,223.0,4498.0,1,72.0,Lord of the Flies,9780571084838 After a plane crash strands them...
2870,9780590956161,0590956167,The Meanest Thing to Say,Bill Cosby;Varnette P. Honeywood,Juvenile Fiction,http://books.google.com/books/content?id=BCaaN...,When a new boy in his second grade class tries...,1997.0,3.53,40.0,956.0,1,29.0,The Meanest Thing to Say,9780590956161 When a new boy in his second gra...
2922,9780618471164,0618471162,"Since 1500, Chapters 15-30",Richard W. Bulliet,Science,http://books.google.com/books/content?id=DS0C7...,The Earth and Its Peoples Brief Edition is a c...,2005.0,4.00,34.0,8.0,1,21.0,"Since 1500, Chapters 15-30: The Earth and Its ...",9780618471164 The Earth and Its Peoples Brief ...
2991,9780671447205,0671447203,The Bluest Eye,Toni Morrison,African Americans,NaN,Tells the story of eleven-year old Pecola Bree...,1972.0,4.01,160.0,239.0,1,54.0,The Bluest Eye,9780671447205 Tells the story of eleven-year o...
3000,9780671631987,0671631985,Teach Your Child to Read in 100 Easy Lessons,Siegfried Engelmann;Phyllis Haddox;Elaine Bruner,Education,http://books.google.com/books/content?id=MUucJ...,"With more than half a million copies in print,...",1986.0,4.15,395.0,2083.0,1,40.0,Teach Your Child to Read in 100 Easy Lessons,9780671631987 With more than half a million co...
3198,9780689716041,0689716044,The Bears on Hemlock Mountain,Alice Dalgliesh,Juvenile Fiction,http://books.google.com/books/content?id=2gt4h...,An eight-year-old boy who is frightened of tra...,1992.0,3.78,64.0,2017.0,1,34.0,The Bears on Hemlock Mountain,9780689716041 An eight-year-old boy who is fri...
3201,9780689823824,0689823827,A Child's Garden of Verses,Robert Louis Stevenson,Juvenile Fiction,http://books.google.com/books/content?id=luTZA...,"Here is a delightful look at childhood, writte...",1999.0,4.30,67.0,21780.0,1,27.0,A Child's Garden of Verses,9780689823824 Here is a delightful look at chi...
3203,9780689834196,0689834195,Salt in His Shoes,Deloris Jordan;Roslyn M. Jordan,Juvenile Nonfiction,http://books.google.com/books/content?id=hYzQw...,"Young Michael Jordan, who is smaller than the ...",2003.0,4.21,32.0,1054.0,1,23.0,Salt in His Shoes: Michael Jordan in Pursuit o...,"9780689834196 Young Michael Jordan, who is sma..."
3213,9780689860072,0689860072,Dragonsinger,Anne McCaffrey,Juvenile Fiction,http://books.google.com/books/content?id=IiLlZ...,"Menolly flees her home, because she is not per...",2003.0,4.28,288.0,34207.0,1,23.0,Dragonsinger,"9780689860072 Menolly flees her home, because ..."
3475,9780747572930,0747572933,A Sound Like Someone Trying Not to Make a Sound,John Irving,Bedtime,http://books.google.com/books/content?id=45_bG...,When a child hears a noise in the night he get...,2004.0,4.01,32.0,664.0,1,22.0,A Sound Like Someone Trying Not to Make a Sound,9780747572930 When a child hears a noise in th...
3580,9780763619312,0763619310,Judy Moody Gets Famous!,Megan McDonald;Peter Reynolds,Juvenile Fiction,http://books.google.com/books/content?id=11tdd...,When a third grade classmate gets her picture ...,2003.0,4.03,144.0,8080.0,1,23.0,Judy Moody Gets Famous!,9780763619312 When a third grade classmate get...
3591,9780764122781,0764122789,Aquatic Turtles,Richard D. Bartlett;Patricia Bartlett,Pets,http://books.google.com/books/content?id=ket2b...,Titles in this series present basic informatio...,2003.0,3.80,46.0,20.0,1,23.0,"Aquatic Turtles: Sliders, Cooters, Painted, an...",9780764122781 Titles in this series present ba...
3667,9780765357663,0765357666,Hidden Talents,David Lubar,Juvenile Fiction,http://books.google.com/books/content?id=wgEFP...,When thirteen-year-old Martin Anderson arrives...,2007.0,3.93,240.0,2333.0,1,19.0,Hidden Talents,9780765357663 When thirteen-year-old Martin An...
3747,9780786808069,0786808063,Baby Einstein: Neighborhood Animals,Marilyn Singer;Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=X9a4P...,Children will discover the exciting world of t...,2001.0,3.89,16.0,180.0,1,25.0,Baby Einstein: Neighborhood Animals,9780786808069 Children will discover the excit...
3748,9780786808373,0786808373,Baby Einstein: Birds,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=0jxHP...,"Introducing your baby to birds, cats, dogs, an...",2002.0,3.78,20.0,9.0,1,24.0,Baby Einstein: Birds,"9780786808373 Introducing your baby to birds, ..."
3749,9780786808380,0786808381,Baby Einstein: Babies,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=jv4NA...,"Introduce your babies to birds, cats, dogs, an...",2002.0,4.03,20.0,29.0,1,24.0,Baby Einstein: Babies,"9780786808380 Introduce your babies to birds, ..."
3750,9780786808397,078680839X,Baby Einstein: Dogs,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=qut8t...,"Introduce your baby to birds, cats, dogs, and ...",2002.0,3.81,20.0,26.0,1,24.0,Baby Einstein: Dogs,"9780786808397 Introduce your baby to birds, ca..."
3751,9780786808717,0786808713,Baby Einstein: What Does Violet See? Raindrops...,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=95IIA...,A very special puddle sets Violet the mouse of...,2002.0,3.25,18.0,16.0,1,24.0,Baby Einstein: What Does Violet See? Raindrops...,9780786808717 A very special puddle sets Viole...
3759,9780786811052,0786811056,Sparrow Hawk Red,Ben Mikaelsen,Adventure stories,http://books.google.com/books/content?id=x0g_6...,"Thirteen-year-old Ricky, the Mexican American ...",1995.0,3.77,185.0,1.0,1,31.0,Sparrow Hawk Red,"9780786811052 Thirteen-year-old Ricky, the Mex..."
3764,9780786818723,0786818727,Baby Einstein: Violet's House,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=bC4HA...,"Violet, a very curious young mouse, invites ba...",2003.0,3.98,10.0,39.0,1,23.0,Baby Einstein: Violet's House: A Giant Touch-a...,"9780786818723 Violet, a very curious young mou..."
3765,9780786819119,0786819111,"Baby Einstein: Water, Water Everywhere","Disney Book Group,",Juvenile Fiction,http://books.google.com/books/content?id=tuAdA...,Charming illustrations and playful rhythmic ve...,2003.0,3.70,10.0,77.0,1,23.0,"Baby Einstein: Water, Water Everywhere",9780786819119 Charming illustrations and playf...
4215,9780887511127,0887511120,Teaching the World's Children,Mary Ashworth;Patricia Wakefield,Education,http://books.google.com/books/content?id=mp4Fh...,The language young children use is the languag...,2004.0,3.50,101.0,4.0,1,22.0,Teaching the World's Children: ESL for Ages Th...,9780887511127 The language young children use ...
4231,9780898599596,0898599598,The Ecological Approach to Visual Perception,James Jerome Gibson,Psychology,http://books.google.com/books/content?id=DrhCC...,This is a book about how we see: the environme...,1986.0,4.28,348.0,122.0,1,40.0,The Ecological Approach to Visual Perception,9780898599596 This is a book about how we see:...
4264,9780941807555,094180755X,The Little Big Book for God's Children,Lena Tabori;Alice Wong,Religion,http://books.google.com/books/content?id=s2PfT...,THE LITTLE BIG BOOK FOR GOD'S CHILDREN is a wo...,2001.0,4.88,352.0,8.0,1,25.0,The Little Big Book for God's Children,9780941807555 THE LITTLE BIG BOOK FOR GOD'S CH...
4596,9781560067849,1560067845,Flowers for Algernon,Patrice Cassedy,Juvenile Nonfiction,http://books.google.com/books/content?id=x_CUf...,"Discusses the young adult book ""Flowers for Al...",2000.0,3.00,96.0,1.0,1,26.0,Flowers for Algernon,"9781560067849 Discusses the young adult book ""..."
4606,9781561709335,1561709336,Power Vs. Force,David R. Hawkins,"Body, Mind & Spirit",http://books.google.com/books/content?id=mBjdV...,In this groundbreaking book you will learn how...,2002.0,4.22,341.0,6696.0,1,24.0,Power Vs. Force: The Hidden Determinants of Hu...,9781561709335 In this groundbreaking book you ...
4808,9781586853334,1586853333,The Big Book of Boy Stuff,Bart King,Juvenile Nonfiction,http://books.google.com/books/content?id=08Ilm...,There's this boy. Let's say he's somewhere bet...,2004.0,4.24,292.0,141.0,1,22.0,The Big Book of Boy Stuff,9781586853334 There's this boy. Let's say he's...
4899,9781593854461,1593854463,Teaching Reading Comprehension to Students wit...,Janette K. Klingner;Sharon Vaughn;Alison Boardman,Education,http://books.google.com/books/content?id=NfLfn...,A ChoiceOutstanding Academic Title! A highly p...,2007.0,3.77,178.0,22.0,1,19.0,Teaching Reading Comprehension to Students wit...,9781593854461 A ChoiceOutstanding Academic Tit...
5120,9781895176407,1895176409,"Galapagos, a Natural History",Michael Hume Jackson,History,http://books.google.com/books/content?id=NXS8c...,This book details the natural history of the p...,1993.0,3.87,336.0,93.0,1,33.0,"Galapagos, a Natural History",9781895176407 This book details the natural hi...